################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

stale_assigned:
    ticket_limit: 10
    stale_days: 30
    warning_days: 7
    warning_label: "stale-assigned"
    done_label: "auto-unassigned"
    warning_comment: |
        I am the [Flink Jira Bot|https://github.com/apache/flink-jira-bot/] and I help the community manage its development. I see this issue is assigned but has not received an update in {stale_days} days, so it has been labeled "{warning_label}".
        If you are still working on the issue, please remove the label and add a comment updating the community on your progress.  If this issue is waiting on feedback, please consider this a reminder to the committer/reviewer. Flink is a very active project, and so we appreciate your patience.
        If you are no longer working on the issue, please unassign yourself so someone else may work on it.

    done_comment: |
        Irrelevant

stale_minor:
    ticket_limit: 10
    stale_days: 180
    warning_days: 7
    warning_label: "stale-minor"
    done_label: "auto-deprioritized-minor"
    warning_comment: |
        I am the [Flink Jira Bot|https://github.com/apache/flink-jira-bot/] and I help the community manage its development. I see this issues has been marked as Minor but is unassigned and neither itself nor its Sub-Tasks have been updated for {stale_days} days. I have gone ahead and marked it "{warning_label}". If this ticket is still Minor, please either assign yourself or give an update. Afterwards, please remove the label or in {warning_days} days the issue will be deprioritized.

    done_comment: |
        This issue was labeled "{warning_label}" {warning_days} days ago and has not received any updates so it is being deprioritized. If this ticket is actually Minor, please raise the priority and ask a committer to assign you the issue or revive the public discussion.

stale_blocker:
    ticket_limit: 5
    stale_days: 1
    warning_days: 7
    warning_label: "stale-blocker"
    done_label: "auto-deprioritized-blocker"
    warning_comment: |
        I am the [Flink Jira Bot|https://github.com/apache/flink-jira-bot/] and I help the community manage its development. I see this issues has been marked as a Blocker but is unassigned and neither itself nor its Sub-Tasks have been updated for {stale_days} days. I have gone ahead and marked it "{warning_label}". If this ticket is a Blocker, please either assign yourself or give an update. Afterwards, please remove the label or in {warning_days} days the issue will be deprioritized.

    done_comment: |
        This issue was labeled "{warning_label}" {warning_days} days ago and has not received any updates so it is being deprioritized. If this ticket is actually a Blocker, please raise the priority and ask a committer to assign you the issue or revive the public discussion.

stale_critical:
    ticket_limit: 10
    stale_days: 14
    warning_days: 7
    warning_label: "stale-critical"
    done_label: "auto-deprioritized-critical"
    warning_comment: |
        I am the [Flink Jira Bot|https://github.com/apache/flink-jira-bot/] and I help the community manage its development. I see this issues has been marked as Critical but is unassigned and neither itself nor its Sub-Tasks have been updated for {stale_days} days. I have gone ahead and marked it "{warning_label}". If this ticket is critical, please either assign yourself or give an update. Afterwards, please remove the label or in {warning_days} days the issue will be deprioritized.

    done_comment: |
        This issue was labeled "{warning_label}" {warning_days} days ago and has not received any updates so it is being deprioritized. If this ticket is actually Critical, please raise the priority and ask a committer to assign you the issue or revive the public discussion.

stale_major:
    ticket_limit: 15
    stale_days: 60
    warning_days: 7
    warning_label: "stale-major"
    done_label: "auto-deprioritized-major"
    warning_comment: |
        I am the [Flink Jira Bot|https://github.com/apache/flink-jira-bot/] and I help the community manage its development. I see this issues has been marked as Major but is unassigned and neither itself nor its Sub-Tasks have been updated for {stale_days} days. I have gone ahead and added a "{warning_label}" to the issue". If this ticket is a Major, please either assign yourself or give an update. Afterwards, please remove the label or in {warning_days} days the issue will be deprioritized.

    done_comment: |
        This issue was labeled "{warning_label}" {warning_days} days ago and has not received any updates so it is being deprioritized. If this ticket is actually Major, please raise the priority and ask a committer to assign you the issue or revive the public discussion.
